# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_admin
      POSTGRES_DB: survey_db
